### ISSUE TITLE
Unable to Connect to tcp://api.qa.koin.in:80

### ISSUE THREAD

**Issue by matneves** [contardi/koin-magento#1]
Olá,

Estava usando o módulo na versão 1.0.0 e atualizei para a sua versão, na esperança que esse problema se resolvesse, porém sem sucesso. Isso ocorre ao finalizar o pedido, ao montar o Zend_Http_Client e executar o request() na linha 43 do Koin/Payment/Model/Service/Abstract.php:

`'Unable to Connect to tcp://api.qa.koin.in:80. Error #110: Connection timed out'`

Já passou por isso? Estou usando o módulo em modo "Teste".

**Comment by contardi** [comment]
Qual a versão do Magento que vocẽ está usando?

**Comment by matneves** [comment]
@contardi, eu uso a 1.9.3.1, mas acabou que o problema era na autorização do sandbox da Koin, que estava desabilitada para minha conta. Eles pediram que eu realizasse os testes direto em produção (também não entendi). Agora está funcionando normalmente.
